name: Test Code Linux

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The full 40-character commit sha to test from netbirdio/netbird'
        required: true
        default: 'e0bed2b0fb29c4abbc6d46191a7f54de90e29122'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || github.actor_id }}
  cancel-in-progress: true

jobs:
  build-cache:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code from upstream
        uses: actions/checkout@v4
        with:
          repository: netbirdio/netbird
          ref: ${{ github.event.inputs.commit_sha }}
          fetch-depth: 0

      # ... rest of steps unchanged ...
